import { numericCssPixels, visualDeclarationKey } from './visualContract'

export type VisualContractBaselineProperty = 'font-size' | 'border-radius' | 'box-shadow' | 'backdrop-filter'

export type VisualContractBaselineEntry = {
  file: string
  selector: string
  property: VisualContractBaselineProperty
  value: string
  calculatedPx: number | null
  replaceable: boolean
  expandedPath: string
  reason: string
  expires: string
}

const LEGACY_EXPIRY = '2027-03-31'

const MIGRATION_PATH: Record<VisualContractBaselineProperty, string> = {
  'font-size': '按信息层级提升到 12px 以上；语义文案优先恢复到 13-14px',
  'border-radius': '按组件层级替换为 --radius-sm、--radius 或 --radius-lg',
  'box-shadow': '按抬升层级替换为现有 --shadow-* 语义 token',
  'backdrop-filter': '仅保留在明确白名单表面；普通面板移除 blur',
}

function legacy(
  file: string,
  selector: string,
  property: VisualContractBaselineProperty,
  value: string,
  reason: string,
): VisualContractBaselineEntry {
  return {
    file,
    selector,
    property,
    value,
    calculatedPx: property === 'font-size' ? numericCssPixels(value) : null,
    replaceable: true,
    expandedPath: MIGRATION_PATH[property],
    reason,
    expires: LEGACY_EXPIRY,
  }
}

/**
 * Historical visual debt is explicit and shrinking-only. A declaration must
 * be removed from this list when its UI is migrated; new declarations cannot
 * enter the list without a reviewed reason and exit date.
 */
export const VISUAL_CONTRACT_BASELINE: readonly VisualContractBaselineEntry[] = [
  legacy("src/components/apps/AppInteractiveTerminal.vue", ".interactive-terminal__composer button", "border-radius", "9px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/apps/AppInteractiveTerminal.vue", ".interactive-terminal__composer input", "border-radius", "9px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/cluster/ClusterNotificationsDialog.vue", ".cluster-notifications__provider-icon", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/common/DnsResolutionGuide.vue", ".dns-guide", "border-radius", "12px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/common/DnsResolutionGuide.vue", ".dns-guide nav i", "border-radius", "4px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/common/DnsResolutionGuide.vue", ".dns-guide__icon", "border-radius", "9px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/common/DnsResolutionGuide.vue", ".dns-guide__records button, .dns-guide nav a", "border-radius", "8px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/docker/DockerDeploymentEditor.vue", ".deployment-diagnostics button", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/docker/DockerDeploymentEditor.vue", ".deployment-editor__scanner", "border-radius", "8px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/docker/DockerDeploymentEditor.vue", ".deployment-editor__surface", "border-radius", "11px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/files/CodeEditor.vue", ".code-search", "border-radius", "8px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/files/CodeEditor.vue", ".code-search__field", "border-radius", "5px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/files/CodeEditor.vue", ".code-search__icon, .code-search__option", "border-radius", "4px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/files/FileShareDialog.vue", ".file-share-dialog__expiry span", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/files/FileShareDialog.vue", ".file-share-dialog__file", "border-radius", "12px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/files/FileShareDialog.vue", ".file-share-dialog__file-icon", "border-radius", "11px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/files/FileShareDialog.vue", ".file-share-dialog__link-row input", "border-radius", "9px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/files/FileShareDialog.vue", ".file-share-dialog__message, .file-share-dialog__error", "border-radius", "9px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/files/FileShareDialog.vue", ".file-share-dialog__notice, .file-share-dialog__one-time, .file-share-dialog__active", "border-radius", "11px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/files/FileShareDialog.vue", ".file-share-dialog__retry", "border-radius", "9px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/files/FileShareManagerDialog.vue", ".file-share-manager__empty-icon", "border-radius", "14px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/files/FileShareManagerDialog.vue", ".file-share-manager__file-icon", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/files/FileShareManagerDialog.vue", ".file-share-manager__intro", "border-radius", "11px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/files/FileShareManagerDialog.vue", ".file-share-manager__list li", "border-radius", "11px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/files/FileShareManagerDialog.vue", ".file-share-manager__message, .file-share-manager__error", "border-radius", "9px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/files/FileShareManagerDialog.vue", ".file-share-manager__state button", "border-radius", "9px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/files/FileShareManagerDialog.vue", ".file-share-manager__stop", "border-radius", "9px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/monitoring/TrendChart.vue", ".trend-chart__tooltip", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/AccountManagementDialog.vue", ".account-card", "border-radius", "12px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/AccountManagementDialog.vue", ".account-card__buttons button, .account-card__keys button", "border-radius", "7px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/AccountManagementDialog.vue", ".account-card__keys li", "border-radius", "8px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/AccountManagementDialog.vue", ".account-manager__form", "border-radius", "12px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/AccountManagementDialog.vue", ".account-manager__summary", "border-radius", "12px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/AccountManagementDialog.vue", ".account-policy-grid button", "border-radius", "12px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/DiskPartitionDialog.vue", ".disk-action-card", "border-radius", "11px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/DiskPartitionDialog.vue", ".disk-action-card input[type='text'], .disk-action-card select", "border-radius", "8px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/DiskPartitionDialog.vue", ".disk-confirm__icon", "border-radius", "12px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/DiskPartitionDialog.vue", ".disk-facts div", "border-radius", "9px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/DiskPartitionDialog.vue", ".disk-job", "border-radius", "11px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/DiskPartitionDialog.vue", ".disk-list, .disk-inspector", "border-radius", "13px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/DiskPartitionDialog.vue", ".disk-protection", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/DiskPartitionDialog.vue", ".disk-row__icon", "border-radius", "9px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/DiskPartitionDialog.vue", ".disk-summary > div", "border-radius", "11px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/FirewallManagerDialog.vue", ".firewall-manager__advanced > summary:focus-visible, .firewall-manager__raw > summary:focus-visible", "border-radius", "6px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/FirewallManagerDialog.vue", ".firewall-manager__control", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/FirewallManagerDialog.vue", ".firewall-manager__decision, .firewall-manager__zone-badge", "border-radius", "7px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/FirewallManagerDialog.vue", ".firewall-manager__filter-bar", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/FirewallManagerDialog.vue", ".firewall-manager__filter-option", "border-radius", "8px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/FirewallManagerDialog.vue", ".firewall-manager__parsed-rule", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/FirewallManagerDialog.vue", ".firewall-manager__parsed-rules", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/FirewallManagerDialog.vue", ".firewall-manager__quick-card", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/FirewallManagerDialog.vue", ".firewall-manager__raw", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/FirewallManagerDialog.vue", ".firewall-manager__raw-rule", "border-radius", "9px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/FirewallManagerDialog.vue", ".firewall-manager__rule-empty", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/FirewallManagerDialog.vue", ".firewall-manager__rule-mode", "border-radius", "8px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/FirewallManagerDialog.vue", ".firewall-manager__rule-mode button", "border-radius", "6px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/FirewallManagerDialog.vue", ".firewall-manager__status-icon, .firewall-manager__control-icon, .firewall-manager__quick-icon", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/FirewallManagerDialog.vue", ".firewall-manager__status, .firewall-manager__section, .firewall-manager__advanced-section", "border-radius", "12px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/FirewallManagerDialog.vue", ".firewall-manager__tab", "border-radius", "8px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/FirewallManagerDialog.vue", ".firewall-manager__tabs", "border-radius", "12px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/FirewallManagerDialog.vue", ".firewall-manager__technical-grid > div", "border-radius", "8px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/PortUsageDialog.vue", ".port-usage-group", "border-radius", "12px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/PortUsageDialog.vue", ".port-usage-group__header", "border-radius", "9px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/PortUsageDialog.vue", ".port-usage-item", "border-radius", "9px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/PortUsageDialog.vue", ".port-usage-item__details code", "border-radius", "7px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/PortUsageDialog.vue", ".port-usage-item__docker", "border-radius", "7px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/SSHDefenseDialog.vue", ".ssh-defense-manager__profiles button", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/SSHDefenseDialog.vue", ".ssh-defense-manager__search, .ssh-defense-manager__trusted-form input", "border-radius", "9px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/SSHDefenseDialog.vue", ".ssh-defense-manager__section", "border-radius", "12px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/SSHDefenseDialog.vue", ".ssh-defense-manager__summary", "border-radius", "12px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/SystemLogsDialog.vue", ".system-log-highlight", "border-radius", "3px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/SystemTuningDialog.vue", ".tuning-item", "border-radius", "12px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/SystemTuningDialog.vue", ".tuning-summary", "border-radius", "12px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/overview/SystemTuningDialog.vue", ".tuning-toolbar button", "border-radius", "8px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/sites/LocalWebServicePicker.vue", ".local-web-service-picker__alert", "border-radius", "9px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/sites/LocalWebServicePicker.vue", ".local-web-service-picker__candidate", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/sites/LocalWebServicePicker.vue", ".local-web-service-picker__icon", "border-radius", "9px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/sites/LocalWebServicePicker.vue", ".local-web-service-picker__scan, .local-web-service-picker__view", "border-radius", "9px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/sites/LocalWebServicePicker.vue", ".local-web-service-picker__toolbar, .local-web-service-picker__results", "border-radius", "12px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/sites/SitesSectionTabs.vue", ".sites-section-tabs", "border-radius", "14px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/sites/SitesSectionTabs.vue", ".sites-section-tabs a", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/terminal/HostTerminal.vue", ".host-terminal__composer button", "border-radius", "8px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/terminal/HostTerminal.vue", ".host-terminal__composer input", "border-radius", "8px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/terminal/TerminalContextMenu.vue", ".terminal-context-menu", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/terminal/TerminalContextMenu.vue", ".terminal-context-menu button", "border-radius", "7px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/terminal/TerminalToolbar.vue", ".terminal-toolbar button", "border-radius", "8px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/AppsView.vue", ".access-card", "border-radius", "12px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/AppsView.vue", ".access-card > span", "border-radius", "11px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/AppsView.vue", ".access-options button", "border-radius", "12px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/AppsView.vue", ".app-card", "border-radius", "14px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/AppsView.vue", ".app-card", "border-radius", "18px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/AppsView.vue", ".app-card__icon", "border-radius", "12px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/AppsView.vue", ".app-card__icon, .app-detail-head__icon", "border-radius", "14px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/AppsView.vue", ".app-control-panel", "border-radius", "16px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/AppsView.vue", ".app-detail-head__icon", "border-radius", "15px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/AppsView.vue", ".app-detail-section", "border-radius", "16px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/AppsView.vue", ".app-install-state", "border-radius", "16px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/AppsView.vue", ".app-job-banner", "border-radius", "16px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/AppsView.vue", ".app-job-banner__icon", "border-radius", "12px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/AppsView.vue", ".app-job-banner__progress, .job-detail-progress i", "border-radius", "99px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/AppsView.vue", ".confirm-app", "border-radius", "14px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/AppsView.vue", ".confirm-app img", "border-radius", "12px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/AppsView.vue", ".domain-list__item", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/AppsView.vue", ".install-more-card", "border-radius", "14px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/AppsView.vue", ".install-more-card", "border-radius", "18px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/AppsView.vue", ".install-more-card > span", "border-radius", "14px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/AppsView.vue", ".market-hero", "border-radius", "14px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/AppsView.vue", ".market-hero", "border-radius", "15px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/AppsView.vue", ".market-search", "border-radius", "12px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/AppsView.vue", ".market-segment", "border-radius", "12px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/AppsView.vue", ".market-segment button", "border-radius", "9px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/AppsView.vue", ".market-toolbar", "border-radius", "14px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/AppsView.vue", ".market-toolbar", "border-radius", "18px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/ClusterShareView.vue", ".share-brand__logo :deep(.brand__mark)", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/ClusterShareView.vue", ".share-card", "border-radius", "18px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/ClusterShareView.vue", ".share-card__header :deep(.os-identity__mark)", "border-radius", "11px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/ClusterShareView.vue", ".share-hero", "border-radius", "18px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/ClusterShareView.vue", ".share-hero", "border-radius", "24px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/ClusterShareView.vue", ".share-metrics > div > i", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/ClusterShareView.vue", ".share-refresh, .share-icon-button, .share-state button", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/ClusterShareView.vue", ".share-view-switch", "border-radius", "11px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/ClusterShareView.vue", ".share-view-switch button", "border-radius", "8px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/ClusterShareView.vue", ".share-warning", "border-radius", "12px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/ClusterView.vue", ".cluster-card__drag", "border-radius", "8px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/ClusterView.vue", ".cluster-card__metrics i", "border-radius", "99px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/ClusterView.vue", ".cluster-hero", "border-radius", "14px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/ClusterView.vue", ".cluster-hero", "border-radius", "15px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/DiagnosticsView.vue", ".diagnostic-card__icon", "border-radius", "9px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/DiagnosticsView.vue", ".diagnostic-command-overview__icon", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/DiagnosticsView.vue", ".diagnostic-command-panel__toggle", "border-radius", "8px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/DiagnosticsView.vue", ".diagnostic-command-rail__item", "border-radius", "9px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/DiagnosticsView.vue", ".diagnostic-command-row", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/DiagnosticsView.vue", ".diagnostic-command-run", "border-radius", "8px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/DiagnosticsView.vue", ".diagnostic-overview__eyebrow > span", "border-radius", "8px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/DiagnosticsView.vue", ".diagnostic-report-card__heading > span, .diagnostic-report-identity__heading > span", "border-radius", "9px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/DiagnosticsView.vue", ".diagnostic-report-section__icon", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/DiagnosticsView.vue", ".diagnostic-score-dimension__icon", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/DiagnosticsView.vue", ".diagnostic-score-dimension__icon", "border-radius", "12px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/DiagnosticsView.vue", ".diagnostic-score-note__icon", "border-radius", "9px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/DiagnosticsView.vue", ".diagnostic-workbench", "border-radius", "14px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/DockerView.vue", ".action-card", "border-radius", "13px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/DockerView.vue", ".backup-list article", "border-radius", "12px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/DockerView.vue", ".compose-environment-card--manager", "border-radius", "12px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/DockerView.vue", ".compose-manager__meta > span", "border-radius", "11px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/DockerView.vue", ".deployment-advanced", "border-radius", "14px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/DockerView.vue", ".deployment-input-card", "border-radius", "15px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/DockerView.vue", ".docker-command-center", "border-radius", "14px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/DockerView.vue", ".docker-command-center__identity .workspace-card__icon", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/DockerView.vue", ".docker-context-menu", "border-radius", "12px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/DockerView.vue", ".docker-context-menu button", "border-radius", "8px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/DockerView.vue", ".docker-group__icon", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/DockerView.vue", ".docker-group__toggle:focus-visible", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/DockerView.vue", ".docker-nav button", "border-radius", "8px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/DockerView.vue", ".docker-row-actions__group", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/DockerView.vue", ".docker-row-actions__group .icon-button", "border-radius", "7px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/DockerView.vue", ".docker-sort", "border-radius", "9px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/DockerView.vue", ".inline-check input[type='checkbox'], .check-row input[type='checkbox']", "border-radius", "5px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/DockerView.vue", ".stats-grid article", "border-radius", "13px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/DockerView.vue", ".text-area", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/DockerView.vue", ".text-input, .select-input", "border-radius", "11px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/DockerView.vue", ".workspace-card", "border-radius", "14px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/DockerView.vue", ".workspace-card", "border-radius", "16px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/DockerView.vue", ".workspace-card__icon", "border-radius", "11px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/EnvironmentView.vue", ".environment-action-grid input", "border-radius", "9px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/EnvironmentView.vue", ".environment-backups article", "border-radius", "12px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/EnvironmentView.vue", ".environment-checks > div, .environment-components article, .environment-action-grid article", "border-radius", "14px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/EnvironmentView.vue", ".environment-empty", "border-radius", "12px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/EnvironmentView.vue", ".environment-hero", "border-radius", "14px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/EnvironmentView.vue", ".environment-hero", "border-radius", "18px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/EnvironmentView.vue", ".environment-install-card, .environment-panel", "border-radius", "16px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/EnvironmentView.vue", ".environment-job-banner", "border-radius", "15px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/EnvironmentView.vue", ".environment-job-banner i", "border-radius", "99px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/EnvironmentView.vue", ".environment-mode-card", "border-radius", "14px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/EnvironmentView.vue", ".environment-switches button", "border-radius", "13px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/EnvironmentView.vue", ".environment-tabs button", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/EnvironmentView.vue", ".environment-update-list article", "border-radius", "12px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/EnvironmentView.vue", ".environment-update-list select", "border-radius", "9px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/EnvironmentView.vue", ".sites-section-tabs, .environment-tabs", "border-radius", "14px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FileShareView.vue", ".file-share-brand__logo :deep(.brand__mark)", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FileShareView.vue", ".file-share-card, .file-share-state", "border-radius", "17px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FileShareView.vue", ".file-share-card, .file-share-state", "border-radius", "22px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FileShareView.vue", ".file-share-download, .file-share-open, .file-share-state button", "border-radius", "11px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FileShareView.vue", ".file-share-expiry", "border-radius", "11px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FileShareView.vue", ".file-share-file__icon", "border-radius", "13px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FileShareView.vue", ".file-share-file__icon", "border-radius", "15px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FileShareView.vue", ".file-share-preview img", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FileShareView.vue", ".file-share-state__icon", "border-radius", "16px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FileShareView.vue", ".file-share-theme", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FilesView.vue", ".batch-bar", "border-radius", "12px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FilesView.vue", ".batch-bar", "border-radius", "14px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FilesView.vue", ".batch-bar button", "border-radius", "8px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FilesView.vue", ".clipboard-bar button", "border-radius", "8px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FilesView.vue", ".clipboard-bar__icon", "border-radius", "9px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FilesView.vue", ".code-editor-tool", "border-radius", "6px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FilesView.vue", ".drop-overlay", "border-radius", "14px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FilesView.vue", ".file-activity-row", "border-radius", "9px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FilesView.vue", ".file-activity-row__actions button", "border-radius", "8px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FilesView.vue", ".file-activity-row__icon", "border-radius", "8px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FilesView.vue", ".file-activity-row__track", "border-radius", "99px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FilesView.vue", ".file-browser", "border-radius", "16px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FilesView.vue", ".file-context-menu", "border-radius", "11px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FilesView.vue", ".file-context-menu", "border-radius", "16px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FilesView.vue", ".file-context-menu button", "border-radius", "7px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FilesView.vue", ".file-grid-card", "border-radius", "13px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FilesView.vue", ".file-grid-card__icon", "border-radius", "20px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FilesView.vue", ".file-grid-card__visual", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FilesView.vue", ".file-grid-sort button, .file-view-switch button", "border-radius", "7px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FilesView.vue", ".file-grid-sort, .file-view-switch", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FilesView.vue", ".file-icon", "border-radius", "9px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FilesView.vue", ".file-internal-drop-hint", "border-radius", "12px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FilesView.vue", ".file-search", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FilesView.vue", ".file-search button, .row-menu", "border-radius", "7px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FilesView.vue", ".file-toolbar", "border-radius", "13px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FilesView.vue", ".media-player", "border-radius", "14px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FilesView.vue", ".media-player, .media-player video", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FilesView.vue", ".media-viewer", "border-radius", "12px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FilesView.vue", ".media-viewer", "border-radius", "16px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FilesView.vue", ".media-viewer iframe", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FilesView.vue", ".media-viewer img", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FilesView.vue", ".media-viewer--pdf iframe", "border-radius", "14px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FilesView.vue", ".operation-form input, .operation-form select", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FilesView.vue", ".remote-download-note", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FilesView.vue", ".remote-download-task", "border-radius", "9px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FilesView.vue", ".remote-download-task progress", "border-radius", "99px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FilesView.vue", ".remote-download-task__icon", "border-radius", "8px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FilesView.vue", ".remote-download-tasks__header button, .remote-download-task__actions button", "border-radius", "9px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/FilesView.vue", ".trash-list", "border-radius", "12px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/LoginView.vue", ".recovery-help pre", "border-radius", "8px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/MonitoringView.vue", ".chart-card, .container-section", "border-radius", "12px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/MonitoringView.vue", ".chart-switch", "border-radius", "9px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/MonitoringView.vue", ".chart-switch button", "border-radius", "6px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/MonitoringView.vue", ".container-charts > article", "border-radius", "11px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/MonitoringView.vue", ".container-compare", "border-radius", "12px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/MonitoringView.vue", ".container-row", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/MonitoringView.vue", ".container-search", "border-radius", "9px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/MonitoringView.vue", ".monitoring-toolbar", "border-radius", "12px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/MonitoringView.vue", ".monitoring-warning", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/MonitoringView.vue", ".monitoring-zoom-strip", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/MonitoringView.vue", ".monitoring-zoom-strip__actions button", "border-radius", "7px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/MonitoringView.vue", ".operator-latency-actions", "border-radius", "9px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/MonitoringView.vue", ".operator-latency-actions button", "border-radius", "6px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/MonitoringView.vue", ".operator-latency-icon", "border-radius", "9px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/MonitoringView.vue", ".range-button", "border-radius", "8px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/MonitoringView.vue", ".selected-container-card", "border-radius", "8px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/MonitoringView.vue", ".summary-card__icon, .section-heading__icon", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/MonitoringView.vue", ".summary-card, .chart-card, .container-section", "border-radius", "14px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/ProcessManagerView.vue", ".process-confirm > span", "border-radius", "12px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/ProcessManagerView.vue", ".process-details dl", "border-radius", "12px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/ProcessManagerView.vue", ".process-details__icon", "border-radius", "11px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/ProcessManagerView.vue", ".process-search", "border-radius", "11px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/ProcessManagerView.vue", ".process-summary__card", "border-radius", "14px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/ProcessManagerView.vue", ".process-summary__card", "border-radius", "16px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/ProcessManagerView.vue", ".process-workspace", "border-radius", "14px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/ProcessManagerView.vue", ".process-workspace", "border-radius", "18px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/TerminalView.vue", ".terminal-alert", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/TerminalView.vue", ".terminal-connections__toggle", "border-radius", "8px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/TerminalView.vue", ".terminal-empty span", "border-radius", "16px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/TerminalView.vue", ".terminal-empty span", "border-radius", "18px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/TerminalView.vue", ".terminal-host", "border-radius", "10px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/TerminalView.vue", ".terminal-host :deep(.terminal-host__os)", "border-radius", "9px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/TerminalView.vue", ".terminal-host-rail", "border-radius", "9px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/TerminalView.vue", ".terminal-host-rail :deep(.terminal-host-rail__os)", "border-radius", "8px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/TerminalView.vue", ".terminal-search input", "border-radius", "9px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/TerminalView.vue", ".terminal-tab", "border-radius", "8px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/TerminalView.vue", ".terminal-tabs-bar__connections", "border-radius", "8px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/views/TerminalView.vue", ".terminal-workspace,.terminal-workspace.is-connections-collapsed", "border-radius", "14px", "历史组件圆角，按层级迁移到语义 radius token"),
  legacy("src/components/cluster/ClusterNotificationsDialog.vue", ".cluster-notifications__switch span::after", "box-shadow", "0 1px 3px rgba(0, 0, 0, .18)", "历史组件阴影，按层级迁移到语义 shadow token"),
  legacy("src/components/docker/DockerDeploymentEditor.vue", ".deployment-editor__surface", "box-shadow", "inset 0 1px 2px rgb(20 48 42 / 4%)", "历史组件阴影，按层级迁移到语义 shadow token"),
  legacy("src/components/files/CodeEditor.vue", ".code-search", "box-shadow", "0 10px 28px rgb(0 0 0 / 38%)", "历史组件阴影，按层级迁移到语义 shadow token"),
  legacy("src/components/terminal/TerminalContextMenu.vue", ".terminal-context-menu", "box-shadow", "0 14px 36px rgb(0 0 0 / 32%)", "历史组件阴影，按层级迁移到语义 shadow token"),
  legacy("src/views/AppsView.vue", ".app-card__icon, .app-detail-head__icon", "box-shadow", "0 5px 14px rgb(16 24 40 / 8%)", "历史组件阴影，按层级迁移到语义 shadow token"),
  legacy("src/views/ClusterShareView.vue", ".share-status i", "box-shadow", "0 0 10px currentColor", "历史组件阴影，按层级迁移到语义 shadow token"),
  legacy("src/views/DiagnosticsView.vue", ".diagnostic-terminal-bar i.is-live", "box-shadow", "0 0 0 4px rgb(54 211 153 / 12%)", "历史组件阴影，按层级迁移到语义 shadow token"),
  legacy("src/views/FilesView.vue", ".batch-bar", "box-shadow", "0 12px 34px rgb(0 0 0 / 20%)", "历史组件阴影，按层级迁移到语义 shadow token"),
  legacy("src/views/FilesView.vue", ".file-context-menu", "box-shadow", "0 18px 52px rgb(0 0 0 / 28%)", "历史组件阴影，按层级迁移到语义 shadow token"),
  legacy("src/views/FilesView.vue", ".file-grid-card__menu", "box-shadow", "0 2px 8px rgb(0 0 0 / 10%)", "历史组件阴影，按层级迁移到语义 shadow token"),
  legacy("src/views/FilesView.vue", ".file-internal-drop-hint", "box-shadow", "0 12px 28px rgb(0 0 0 / 20%)", "历史组件阴影，按层级迁移到语义 shadow token"),
  legacy("src/views/FilesView.vue", ".media-player", "box-shadow", "0 18px 46px rgb(0 0 0 / 30%)", "历史组件阴影，按层级迁移到语义 shadow token"),
  legacy("src/views/FilesView.vue", ".media-viewer img", "box-shadow", "0 18px 46px rgb(0 0 0 / 24%)", "历史组件阴影，按层级迁移到语义 shadow token"),
  legacy("src/views/ProcessManagerView.vue", ".process-live i, .process-state i", "box-shadow", "0 0 0 3px color-mix(in srgb, currentColor 12%, transparent)", "历史组件阴影，按层级迁移到语义 shadow token"),
  legacy("src/views/TerminalView.vue", ".terminal-tab__status", "box-shadow", "0 0 0 2px color-mix(in srgb,currentColor 10%,transparent)", "历史组件阴影，按层级迁移到语义 shadow token"),
  legacy("src/components/apps/AppInteractiveTerminal.vue", ".interactive-terminal header small", "font-size", "11px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/components/apps/AppInteractiveTerminal.vue", ".interactive-terminal__actions > span", "font-size", "11px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/components/common/DnsResolutionGuide.vue", ".dns-guide header small, .dns-guide p, .dns-guide nav > span", "font-size", "11px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/components/common/DnsResolutionGuide.vue", ".dns-guide nav a", "font-size", "11px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/components/common/DnsResolutionGuide.vue", ".dns-guide nav i", "font-size", "9px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/components/common/DnsResolutionGuide.vue", ".dns-guide__records b", "font-size", "10px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/components/common/DnsResolutionGuide.vue", ".dns-guide--compact nav > span, .dns-guide--compact nav a", "font-size", "10px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/components/docker/DockerDeploymentEditor.vue", ".deployment-diagnostics strong", "font-size", ".72rem", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/components/files/CodeEditor.vue", ".code-search__message", "font-size", "10px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/components/monitoring/TrendChart.vue", ".trend-chart__axis", "font-size", ".72rem", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/components/monitoring/TrendChart.vue", ".trend-chart__tick", "font-size", "10.5px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/components/monitoring/TrendChart.vue", ".trend-chart__tooltip time", "font-size", ".72rem", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/components/overview/AccountManagementDialog.vue", ".account-card__badges > span", "font-size", "11px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/components/overview/PortUsageDialog.vue", ".port-usage-group__header span, .port-usage-group__header small", "font-size", "10px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/components/overview/PortUsageDialog.vue", ".port-usage-item__details", "font-size", "10px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/components/overview/PortUsageDialog.vue", ".port-usage-item__docker-header span", "font-size", "10px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/components/overview/PortUsageDialog.vue", ".port-usage-item__docker-meta", "font-size", "10px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/components/overview/PortUsageDialog.vue", ".port-usage-item__facts dd", "font-size", "11px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/components/overview/PortUsageDialog.vue", ".port-usage-item__port-label, .port-usage-item__facts dt", "font-size", "10px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/components/overview/SystemTuningDialog.vue", ".tuning-item__number", "font-size", "11px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/components/overview/SystemTuningDialog.vue", ".tuning-item__risk, .tuning-item__ready", "font-size", "11px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/AppsView.vue", ".access-card small", "font-size", "11px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/AppsView.vue", ".app-card__meta em, .source-pill", "font-size", "10px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/AppsView.vue", ".app-card__recent", "font-size", "10px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/AppsView.vue", ".app-card__runtime", "font-size", "11px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/AppsView.vue", ".app-detail-section > header small", "font-size", "11px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/AppsView.vue", ".job-detail-summary small", "font-size", "11px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/AppsView.vue", ".market-categories button span", "font-size", "11px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/AppsView.vue", ".market-result", "font-size", "11px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/ClusterShareView.vue", ".share-footer", "font-size", "10px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/ClusterShareView.vue", ".share-kicker", "font-size", "11px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/ClusterShareView.vue", ".share-stats span", "font-size", "11px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/ClusterView.vue", ".cluster-access small", "font-size", "11px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/ClusterView.vue", ".cluster-access__controllers code", "font-size", "10px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/ClusterView.vue", ".cluster-access__token pre", "font-size", "11px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/ClusterView.vue", ".cluster-light-enrollment small", "font-size", "11px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/ClusterView.vue", ".cluster-light-enrollment__command pre", "font-size", "10px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/ClusterView.vue", ".cluster-manage__identity code", "font-size", "11px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/ClusterView.vue", ".cluster-manage__identity span", "font-size", "11px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/ClusterView.vue", ".cluster-share__link pre", "font-size", "11px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/ClusterView.vue", ".cluster-share__switch small, .cluster-share__privacy small, .cluster-share__link small, .cluster-share__hint", "font-size", "11px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/DockerView.vue", ".compose-environment-card__required, .compose-environment-card__default", "font-size", ".72rem", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/DockerView.vue", ".docker-group__summary small", "font-size", ".72rem", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/DockerView.vue", ".docker-nav button small", "font-size", ".7rem", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/EnvironmentView.vue", ".environment-components code", "font-size", "11px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/FilesView.vue", ".batch-bar button", "font-size", "11px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/FilesView.vue", ".file-grid-card > small", "font-size", "11px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/FilesView.vue", ".file-name small, .file-row > span > small", "font-size", "11px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/LoginView.vue", ".recovery-help pre", "font-size", "11px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/MonitoringView.vue", ".chart-switch button", "font-size", ".72rem", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/MonitoringView.vue", ".container-row small", "font-size", ".7rem", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/MonitoringView.vue", ".container-row__title em", "font-size", ".62rem", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/MonitoringView.vue", ".container-selection-error", "font-size", ".7rem", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/MonitoringView.vue", ".container-selection-note", "font-size", ".68rem", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/MonitoringView.vue", ".line-style-key", "font-size", ".66rem", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/MonitoringView.vue", ".monitoring-footnote", "font-size", ".74rem", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/MonitoringView.vue", ".monitoring-toolbar__meta", "font-size", ".7rem", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/MonitoringView.vue", ".monitoring-zoom-strip__actions button", "font-size", ".72rem", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/MonitoringView.vue", ".operator-latency-actions button", "font-size", ".7rem", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/MonitoringView.vue", ".operator-latency-heading small", "font-size", ".72rem", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/MonitoringView.vue", ".operator-latency-note", "font-size", ".7rem", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/MonitoringView.vue", ".operator-route", "font-size", ".72rem", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/MonitoringView.vue", ".operator-route small", "font-size", ".66rem", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/MonitoringView.vue", ".selected-container-card > small", "font-size", ".66rem", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/MonitoringView.vue", ".selected-container-card > strong", "font-size", ".72rem", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/MonitoringView.vue", ".summary-card small", "font-size", ".7rem", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/ProcessManagerView.vue", ".process-details > p", "font-size", "10px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/ProcessManagerView.vue", ".process-details dd", "font-size", "11px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/ProcessManagerView.vue", ".process-details dt", "font-size", "10px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/ProcessManagerView.vue", ".process-details header small", "font-size", "10px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/ProcessManagerView.vue", ".process-summary__card > small", "font-size", "11px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/ProcessManagerView.vue", ".process-table td:first-child small", "font-size", "10px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/ProcessManagerView.vue", ".process-table th button, .process-table th > span", "font-size", "10px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/ProcessManagerView.vue", ".process-table__metric strong", "font-size", "11px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
  legacy("src/views/ProcessManagerView.vue", ".process-toolbar__status", "font-size", "11px", "历史紧凑文字，按受影响页面迁移到 12px 以上"),
]

export function baselineKey(entry: VisualContractBaselineEntry): string {
  return visualDeclarationKey(entry)
}
